//CartScreen constant
const CART_ADD_ITEM = 'CARD_ADD_ITEM';
const CART_FAIL_ITEM = 'CART_FAIL_ITEM';
const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

//ShippingScreen constant
const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';

//PaymentScreen Constant
const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';

export {CART_ADD_ITEM, CART_FAIL_ITEM, CART_REMOVE_ITEM, CART_SAVE_SHIPPING, CART_SAVE_PAYMENT};